### ISSUE TITLE
`filterStandardHeaders` is undefined in `addRequestHeaders`

### ISSUE THREAD

**Issue by Mekacher-Anis** [jonluca/har-to-openapi#1]
Even if the flag `filterStandardHeaders` is set to true, it becomes `undefined` in `filterStandardHeaders` when processing mutiple specs and that leads to some standard headers getting included as parameters in the `spec.post.parameters`.
As a workaround I changed this
```TS
const customHeaders = filterStandardHeaders
    ? headers.filter((header) => {
        return !shouldFilterHeader(header.name, securityHeaders);
      })
    : headers;
```
To this
```TS
const customHeaders = (filterStandardHeaders ?? true)
    ? headers.filter((header) => {
        return !shouldFilterHeader(header.name, securityHeaders);
      })
    : headers;
```

**Comment by jonluca** [comment]
Can you post an example where that's true? Are you importing that function directly, or are you saying it occurs through the export in `index.ts`?

AFAICT in the code `internalConfig` always sets that property to default-true

```ts
internalConfig.filterStandardHeaders ??= true;
```

and that it is never reassigned, so I'm not sure how it could be changed. Can you show the HAR where this occurs?

**Comment by jonluca** [comment]
Closing this due to unable to repro
